apiVersion: v2
description: Portal Composition Page generic
icon: https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg
name: portal-composition-page-generic
type: application
version: 1.0.0
