# apiVersion: templates.krateo.io/v1
# kind: RESTAction
# metadata:
#   name: {{ .Values.global.compositionName }}-get-pods-to-create-delete-resources-restart-restaction
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   api:
#   - name: getPods
#     path: ${ "/api/v1/namespaces/{{ .Values.global.compositionName }}/pods"}
#     continueOnError: true
#     filter: >-
#       (
#         [ .getPods.items[] ]
#         | map({name: .metadata.name + "-restart", namespace: "{{ .Values.global.podsLogsPanelNamespace }}"})
#       ) 
#   - name: getButtons
#     continueOnError: true
#     errorKey: getButtonsError
#     path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/{{ .Values.global.podsLogsPanelNamespace }}/buttons?labelSelector=krateo.io%2Fmanaged-by%3D{{ .Values.global.compositionName }}-button-for-restart-pods" }
#     filter: "(.getButtons.items? // []) | map({name: .metadata.name, namespace: .metadata.namespace})"
#   - name: getParagraphs
#     continueOnError: true
#     errorKey: getParagraphsError
#     path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/{{ .Values.global.podsLogsPanelNamespace }}/markdowns?labelSelector=krateo.io%2Fmanaged-by%3D{{ .Values.global.compositionName }}-paragraph-for-restart-pods" }
#     filter: "(.getParagraphs.items? // []) | map({name: .metadata.name, namespace: .metadata.namespace})"
#   - name: getRestaction
#     continueOnError: true
#     errorKey: getRestactionError
#     path: ${ "/apis/templates.krateo.io/v1/namespaces/{{ .Values.global.podsLogsPanelNamespace }}/restactions?labelSelector=krateo.io%2Fmanaged-by%3D{{ .Values.global.compositionName }}-restaction-for-restart-pods" }
#     filter: "(.getRestaction.items? // []) | map({name: .metadata.name, namespace: .metadata.namespace})"
#   filter: >
#     (.getButtons // []) as $buttons
#     | (.getPods // []) as $pods
#     | (.getParagraphs // []) as $paragraphs
#     | (.getRestaction // []) as $restactions
#     | {
#         buttons: {
#           buttonsToCreate: (
#             $pods
#             | map(select(
#                 (.name, .namespace) as $podspair
#                 | all($buttons[]; (.name, .namespace) != $podspair)
#               ))
#             | unique_by(.name, .namespace)
#           ),
#           buttonsToDelete: (
#             $buttons
#             | map(select(
#                 (.name, .namespace) as $buttonspair
#                 | all($pods[]; (.name, .namespace) != $buttonspair)
#               ))
#             | unique_by(.name, .namespace)
#           )
#         },
#         paragraphs: {
#           paragraphsToCreate: (
#             $pods
#             | map(select(
#                 (.name, .namespace) as $podspair
#                 | all($paragraphs[]; (.name, .namespace) != $podspair)
#               ))
#             | unique_by(.name, .namespace)
#           ),
#           paragraphsToDelete: (
#             $paragraphs
#             | map(select(
#                 (.name, .namespace) as $paragraphspair
#                 | all($pods[]; (.name, .namespace) != $paragraphspair)
#               ))
#             | unique_by(.name, .namespace)
#           )
#         },
#         restactions: {
#           restactionsToCreate: (
#             $pods
#             | map(select(
#                 (.name, .namespace) as $podspair
#                 | all($restactions[]; (.name, .namespace) != $podspair)
#               ))
#             | unique_by(.name, .namespace)
#           ),
#           restactionsToDelete: (
#             $restactions
#             | map(select(
#                 (.name, .namespace) as $restactionspair
#                 | all($pods[]; (.name, .namespace) != $restactionspair)
#               ))
#             | unique_by(.name, .namespace)
#           )
#         }
#       }