apiVersion: widgets.templates.krateo.io/v1beta1
kind: Panel
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-panel
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    actions: {}
    items:
      - resourceRefId: composition-overview-row-first
      - resourceRefId: composition-overview-row-second
  resourcesRefs:
    items:
      - id: composition-overview-row-first
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-first
        namespace: {{ .Values.global.compositionNamespace }}
        resource: rows
        verb: GET
      - id: composition-overview-row-second
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-second
        namespace: {{ .Values.global.compositionNamespace }}
        resource: rows
        verb: GET