apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-devs-{{ .Values.global.compositionName }}-get-gateway-resources-in-namespace
  namespace: {{ .Values.global.compositionNamespace }}
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["Gateway","HTTPRoute"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.gke.io"]
  resources: ["GCPBackendPolicy", "HealthCheckPolicy", "daemonsets"]
  verbs: ["get", "list", "watch"]