# RESTACTION PER ELIMINARE RISORSE NON PIù NECESSARIE


apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-delete-all-builds-id-restaction
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: listResourcesToCreateandDelete
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionName }}-gcp-get-builds-to-create-delete-resources-restaction&namespace={{ .Values.global.compositionNamespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: listResourcesToCreateandDeleteError
    exportJwt: true
    filter: ".listResourcesToCreateandDelete.status? // {}"
  - name: deleteLoopButtons
    verb: DELETE
    dependsOn:
      name: listResourcesToCreateandDelete
      iterator: .listResourcesToCreateandDelete.buttons.buttonsToDelete
    path: ${ "/call?apiVersion=widgets.templates.krateo.io/v1beta1&resource=buttons&name=" + (.name + "-buildid-button" ) + "&namespace=" + (.namespace) }
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    exportJwt: true
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: deleteErrors
  - name: deleteLoopRestactions
    verb: DELETE
    dependsOn:
      name: listResourcesToCreateandDelete
      iterator: .listResourcesToCreateandDelete.restactions.restactionsToDelete
    path: ${ "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=" + (.name + "-buildid-restactions") + "&namespace=" + (.namespace) }
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    exportJwt: true
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: deleteErrors
  - name: deleteLoopyamlviewers
    verb: DELETE
    dependsOn:
      name: listResourcesToCreateandDelete
      iterator: .listResourcesToCreateandDelete.yamlviewers.yamlviewersToDelete
    path: ${ "/call?apiVersion=widgets.templates.krateo.io/v1beta1&resource=yamlviewers&name=" + (.name + "-buildid-yamlviewers") + "&namespace=" + (.namespace) }
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    exportJwt: true
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: deleteErrors
