apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    krateo.io/verbose: "true"
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-create-all-builds-id-restaction
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: listBuilds
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionName }}-gcp-get-builds-to-create-delete-resources-restaction&namespace={{ .Values.global.compositionNamespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: listBuildsError
    exportJwt: true
    filter: ".listBuilds.status? // {}"
  - name: createrestactions
    continueOnError: true
    errorKey: createrestactionsError
    dependsOn: 
      name: listBuilds
      iterator: .listBuilds.restactions.restactionsToCreate
    path: ${ "/apis/templates.krateo.io/v1/namespaces/" + (.namespace ) + "/restactions/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "RESTAction",
          "apiVersion": "templates.krateo.io/v1",
          "metadata": {
            "name": .name + "-buildid-restactions",
            "namespace": .namespace,
            "labels": {
              "krateo.io/managed-by": "{{ .Values.global.compositionName }}-restactions-for-builds"
            }
          },
          "spec": {
            "api": [
              {
                "name": "gcploggingrestaction",
                "path": "/v2/entries:list",
                "verb": "POST",
                "endpointRef": {
                  "name": "gcp-endpoint-logging",
                  "namespace": "{{ .Values.global.krateoNamespace }}"
                },
                "payload": "{ \"resourceNames\": [\"projects/{{ .Values.global.projectID }}\"], \"filter\": \"resource.type=\\\"build\\\" AND resource.labels.build_id=\\\"" + (.name | rtrimstr("-buildid-restactions")) + "\\\"\", \"orderBy\": \"timestamp desc\", \"pageSize\": 10000 }",
                "continueOnError": true
              }
            ],
            "filter": "{ \"logs\": (.gcploggingrestaction.entries | reverse | [.[] | .textPayload ]) }"
          }
        }
      }
  - name: createButton
    continueOnError: true
    errorKey: createButtonError
    dependsOn: 
      name: listBuilds
      iterator: .listBuilds.buttons.buttonsToCreate
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.namespace ) + "/buttons/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "Button",
          "apiVersion": "widgets.templates.krateo.io/v1beta1",
          "metadata": {
            "name": .name + "-buildid-button",
            "namespace": .namespace,
            "labels": {
              "krateo.io/managed-by": "{{ .Values.global.compositionName }}-button-for-builds"
            }
          },
          "spec": {
            "widgetData": {
              "label": "Logs",
              "icon": "fa-solid fa-list",
              "size": "middle",
              "type": "primary",
              "clickActionId": "open",
              "actions": {
                "openModal": [
                  {
                    "id": "open",
                    "resourceRefId": "yamlviewers",
                    "type": "openModal",
                    "title": "Logs for: " + .name,
                    "size": "large"
                  }
                ]
              }
            },
            "resourcesRefs": {
              "items": [
                {
                  "id": "yamlviewers",
                  "apiVersion": "widgets.templates.krateo.io/v1beta1",
                  "resource": "yamlviewers",
                  "name": .name + "-buildid-yamlviewers",
                  "namespace": .namespace,
                  "verb": "GET"
                }
              ]
            }
          }
        }
      }
  - name: createyamlviewers
    continueOnError: true
    errorKey: createyamlviewersError
    dependsOn: 
      name: listBuilds
      iterator: .listBuilds.yamlviewers.yamlviewersToCreate
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.namespace ) + "/yamlviewers/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "YamlViewer",
          "apiVersion": "widgets.templates.krateo.io/v1beta1",
          "metadata": {
            "name": .name + "-buildid-yamlviewers",
            "namespace": .namespace,
            "labels": {
              "krateo.io/managed-by": "{{ .Values.global.compositionName }}-yamlviewers-for-builds"
            }
          },
          "spec": {
            "widgetData": {
              json: "{}"
            },
            apiRef: {
              "name": .name + "-buildid-restactions",
              "namespace": .namespace
            },
            "widgetDataTemplate":[
                {
                  "forPath": "json",
                  "expression": "${ .logs | tojson }"
                }
              ]
          }
        }
      }