kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-application-status-panel
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    actions: {}
    items:
      - resourceRefId: application-status-panel-flowchart
  resourcesRefs:
    items:
      - id: application-status-panel-flowchart
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-application-status-panel-flowchart
        namespace: {{ .Values.global.compositionNamespace }}
        resource: flowcharts
        verb: GET