# # RESTACTION CHE SERVE PER ANDARE A RECUPERARE TUTTI GLI ID DELLE BUILD ESEGUITE DATO UN DETERMINATO NOME DI UN TRIGGER.
# # UNA VOLTA CHE HA OTTENUTO I BUILDID CREA UNA LISTA DI BOTTONI DA CREARE E DA ELIMINARE
# apiVersion: templates.krateo.io/v1
# kind: RESTAction
# metadata:
#   name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-get-builds-id-button-restaction
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   api:
#   - name: namespaces
#     path: "/api/v1/namespaces"
#     filter: "[.namespaces.items[] | .metadata.name]"
#     continueOnError: true
#   - name: pods
#     dependsOn:
#       iterator: .[]
#       name: namespaces
#     path: ${ "/api/v1/namespaces/" + (.) + "/pods"}
#     continueOnError: true
#   - name: getBuilds
#     verb: GET
#     continueOnError: true
#     path: "/v1/projects/{{ .Values.global.projectID }}/locations/{{ .Values.global.projectLocation }}/builds"
#     endpointRef:
#       name: gcp-endpoint-cloudbuild
#       namespace: {{ .Values.global.krateoNamespace }}
#     filter: >-
#       (
#         .getBuilds.builds
#         | map(select(.substitutions.TRIGGER_NAME == "{{ .Values.global.compositionName }}-trigger"))
#         | map({name: .id + "-buildid-button", namespace: "{{ .Values.global.buildPanelNamespace }}"})
#       )
#       | .[:3]
#   - name: getButtons
#     continueOnError: true
#     errorKey: getButtonsError
#     path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/{{ .Values.global.buildPanelNamespace }}/buttons?labelSelector=krateo.io%2Fmanaged-by%3D{{ .Values.global.compositionName }}-button-for-builds" }
#     filter: "(.getButtons.items? // []) | map({name: .metadata.name, namespace: .metadata.namespace})"
#   filter: >
#     (.getButtons // []) as $b
#     | (.getBuilds // []) as $p
#     | {
#         buttonsToCreate: (
#           $p
#           | map(select(
#               (.name, .namespace) as $ppair
#               | all($b[]; (.name, .namespace) != $ppair)
#             ))
#           | unique_by(.name, .namespace)
#         ),
#         buttonsToDelete: (
#           $b
#           | map(select(
#               (.name, .namespace) as $bpair
#               | all($p[]; (.name, .namespace) != $bpair)
#             ))
#           | unique_by(.name, .namespace)
#         )
#       }