# apiVersion: templates.krateo.io/v1
# kind: RESTAction
# metadata:
#   name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-get-builds-id-restaction-restaction
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   api:
#   - name: getBuilds
#     verb: GET
#     continueOnError: true
#     path: "/v1/projects/{{ .Values.global.projectID }}/locations/{{ .Values.global.projectLocation }}/builds"
#     endpointRef:
#       name: gcp-endpoint-cloudbuild
#       namespace: {{ .Values.global.krateoNamespace }}
#     filter: >-
#       (
#         .getBuilds.builds
#         | map(select(.substitutions.TRIGGER_NAME == "{{ .Values.global.compositionName }}-trigger"))
#         | map({name: .id + "-buildid-restactions", namespace: "{{ .Values.global.buildPanelNamespace }}"})
#       )
#       | .[:3]
#   - name: getrestaction
#     continueOnError: true
#     errorKey: getrestactionError
#     path: ${ "/apis/templates.krateo.io/v1/namespaces/{{ .Values.global.buildPanelNamespace }}/restactions?labelSelector=krateo.io%2Fmanaged-by%3D{{ .Values.global.compositionName }}-restactions-for-builds" }
#     filter: "(.getrestaction.items? // []) | map({name: .metadata.name, namespace: .metadata.namespace})"
#   filter: >
#     (.getrestaction // []) as $b
#     | (.getBuilds // []) as $p
#     | {
#         restactionsToCreate: (
#           $p
#           | map(select(
#               (.name, .namespace) as $ppair
#               | all($b[]; (.name, .namespace) != $ppair)
#             ))
#           | unique_by(.name, .namespace)
#         ),
#         restactionsToDelete: (
#           $b
#           | map(select(
#               (.name, .namespace) as $bpair
#               | all($p[]; (.name, .namespace) != $bpair)
#             ))
#           | unique_by(.name, .namespace)
#         )
#       }
