# apiVersion: templates.krateo.io/v1
# kind: RESTAction
# metadata:
#   name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-delete-all-builds-id-restaction
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   api:
#   - name: getButtonsList # eliminazione bottoni non necessari
#     verb: GET
#     path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-create-all-builds-id-restaction&namespace={{ .Values.global.compositionNamespace }}"
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     filter: "(.getButtonsList.status.listBuildsandButtons.buttonsToDelete // [])"
#   - name: deleteLoopButtons
#     verb: DELETE
#     dependsOn:
#       name: getButtonsList
#       iterator: .getButtonsList
#     path: ${ "/call?apiVersion=widgets.templates.krateo.io/v1beta1&resource=buttons&name=" + (.name) + "&namespace=" + (.namespace) }
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     continueOnError: true
#     errorKey: deleteErrors
#   - name: getRestactionsList # eliminazione restaction non necessarie
#     verb: GET
#     path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-create-all-builds-id-restaction&namespace={{ .Values.global.compositionNamespace }}"
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     filter: "( .getRestactionsList.status.listBuildsandrestactions.restactionsToDelete // [])"
#   - name: deleteLoopRestactions
#     verb: DELETE
#     dependsOn:
#       name: getRestactionsList
#       iterator: .getRestactionsList
#     path: ${ "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=" + (.name) + "&namespace=" + (.namespace) }
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     continueOnError: true
#     errorKey: deleteErrors
#   - name: getYamlviewersList # eliminazione yamlviewer non necessari
#     verb: GET
#     path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-create-all-builds-id-restaction&namespace={{ .Values.global.compositionNamespace }}"
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     filter: "(.getYamlviewersList.status.listBuildsandyamlviewers.yamlviewersToDelete // [])"
#   - name: deleteLoopYamlviewers
#     verb: DELETE
#     dependsOn:
#       name: getYamlviewersList
#       iterator: .getYamlviewersList
#     path: ${ "/call?apiVersion=widgets.templates.krateo.io/v1beta1&resource=yamlviewers&name=" + (.name) + "&namespace=" + (.namespace) }
#     endpointRef:
#       name: snowplow-endpoint
#       namespace: {{ .Values.global.compositionNamespace }}
#     exportJwt: true
#     headers:
#     - 'Accept: application/json'
#     continueOnError: true
#     errorKey: deleteErrors