kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-documentation-panel
  namespace: {{ .Values.global.compositionNamespace }}
spec: 
  widgetData:
    actions: {}
    items:
      - resourceRefId: composition-documentation-panel-markdown
  resourcesRefs:
    items:
      - id: composition-documentation-panel-markdown
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-documentation-panel-markdown
        namespace: {{ .Values.global.compositionNamespace }}
        resource: markdowns
        verb: GET