apiVersion: widgets.templates.krateo.io/v1beta1
kind: Markdown
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-first-panel-intro-markdown
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    markdown: |
      # Project: {{ .Values.global.compositionName }} 
      This page provides an overview of the composition status and related metrics.