apiVersion: widgets.templates.krateo.io/v1beta1
kind: Panel
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-first-panel-intro
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    actions: {}
    items:
      - resourceRefId: composition-overview-row-first-panel-intro-markdown
  resourcesRefs:
    items:
      - id: composition-overview-row-first-panel-intro-markdown
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-first-panel-intro-markdown
        namespace: {{ .Values.global.compositionNamespace }}
        resource: markdowns
        verb: GET