# file momentaneo per tabella log


# kind: Button
# apiVersion: widgets.templates.krateo.io/v1beta1
# metadata:
#   name: {{ .Values.global.compositionName }}-composition-panel-pods-logs-restart-template
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   widgetData:
#     icon: fa-rotate-right
#     type: default
#     size: small
#     clickActionId: test
#     actions: {}
#   resourcesRefs:
#     items: []

# ---

# kind: Button
# apiVersion: widgets.templates.krateo.io/v1beta1
# metadata:
#   name: {{ .Values.global.compositionName }}-composition-panel-pods-logs-old-logs-template
#   namespace: {{ .Values.global.compositionNamespace }}
# spec:
#   widgetData:
#     clickActionId: open
#     icon: fa-solid fa-list
#     label: Old Logs
#     size: middle
#     type: primary
#     clickActionId: test
#     actions: {}
#   resourcesRefs:
#     items: []