
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-list-all-resources-to-page-pods-restaction
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: getPods
    path: ${ "/api/v1/namespaces/{{ .Values.global.compositionName }}/pods"}
    continueOnError: true
    filter: >-
      (
        [ .getPods.items[] ]
        | map({name: .metadata.name, namespace: .metadata.namespace, deployment: .spec.containers[].name, status: .status.phase  })
      ) 
  - name: createall # create all resources
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-create-all-resources-to-page-pods-restaction&namespace={{ .Values.global.compositionNamespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    exportJwt: true
  - name: deleteall # delete all resources not in use
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name={{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-delete-all-resources-to-page-pods-restaction&namespace={{ .Values.global.compositionNamespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    exportJwt: true
  filter: >-
    {
      pods: (
        .getPods
      ),
      list: (
        .getPods
        | map(
            [
              {
                "valueKey": "deploymentName",
                "kind": "jsonSchemaType",
                "type": "string",
                "stringValue": .deployment
              },
              {
                "valueKey": "podName",
                "kind": "jsonSchemaType",
                "type": "string",
                "stringValue": .name
              },
              {
                "valueKey": "status",
                "kind": "jsonSchemaType",
                "type": "string",
                "stringValue": .status
              },
              {
                valueKey: "logs_button",
                kind: "widget",
                resourceRefId: .name
              }
            ]
          )
        )
    }