apiVersion: widgets.templates.krateo.io/v1beta1
kind: Panel
metadata:
  name: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column-panel
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    actions: {}
    icon:
      name: fa-code-branch
      color: blue
    title: Latest Build
    items:
      - resourceRefId: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column-panel-markdown
  resourcesRefs:
    items:
      - id: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column-panel-markdown
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column-panel-markdown
        namespace: {{ .Values.global.compositionNamespace }}
        resource: markdowns
        verb: GET