apiVersion: widgets.templates.krateo.io/v1beta1
kind: Row
metadata:
  name: {{ .Values.global.compositionName }}-composition-overview-row-third
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    allowedResources:
      - columns
    items: 
      - resourceRefId: {{ .Values.global.compositionName }}-composition-overview-row-third-cve-column
        size: 24
#      - resourceRefId: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column
#        size: 16
  resourcesRefs:
    items: 
      - id: {{ .Values.global.compositionName }}-composition-overview-row-third-cve-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionName }}-composition-overview-row-third-cve-column
        namespace: {{ .Values.global.compositionNamespace }}
        resource: columns
        verb: GET
      - id: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionName }}-composition-overview-row-third-build-column
        namespace: {{ .Values.global.compositionNamespace }}
        resource: columns
        verb: GET