apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-builds-panel-table
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  apiRef:
    name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-gcp-composition-builds-restaction
    namespace: {{ .Values.global.compositionNamespace }}
  widgetData:
    allowedResources:
      - buttons
    columns:
      - title: Status
        valueKey: status
      - title: ID
        valueKey: id
      - title: Trigger
        valueKey: triggername
      - title: Execution Time
        valueKey: lanciataIl
      - title: Logs
        valueKey: logs_button
    data: []
  widgetDataTemplate:
    - forPath: data
      expression: ${ .list }
  resourcesRefsTemplate:
    - iterator: ${ .buildsId }
      template:
        id: ${ .name }
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: buttons
        namespace: ${ .namespace }
        name: ${ .name }
        verb: GET