apiVersion: widgets.templates.krateo.io/v1beta1
kind: Panel
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-third-cve-column-panel
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    actions: {}
    icon:
      name: fa-bug
      color: blue
    title: Vulnerabilities Found
    items:
      - resourceRefId: composition-overview-row-third-cve-column-piechart
  resourcesRefs:
    items:
      - id: composition-overview-row-third-cve-column-piechart
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-third-cve-column-piechart
        namespace: {{ .Values.global.compositionNamespace }}
        resource: piecharts
        verb: GET