apiVersion: widgets.templates.krateo.io/v1beta1
kind: PieChart
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-second-panel-row-pie-chart-application
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  apiRef:
    name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-overview-row-second-panel-row-pie-chart-application-action
    namespace: {{ .Values.global.compositionNamespace }}
  widgetData:
    title: "10"
    description: "Application"
    series:
      total: 0
      data: []
  widgetDataTemplate:
    - forPath: series
      expression: >
        ${
          .getNodes |
          {
            "total": (.ready + .notReady),
            "data": [
              {
                "label": "Ready",
                "value": .ready,
                "color": "green"
              },
              {
                "label": "Not Ready",
                "value": .notReady,
                "color": "red"
              }
            ]
          }
        }
    - expression: ${ (.getNodes.ready + .getNodes.notReady) | tostring }
      forPath: title
